export const services = ['AI Data Collection','Audio Annotation','Image Annotation','Video Annotation','Transcription','Translation','LLM Annotation','RLHF','AI Model Evaluation','Website Development','Mobile App Development','Custom Software Development','CRM/ERP Development','SaaS Development','API Integration','AI Chatbot Development','IT Consulting'];
export const leadStatuses = ['New','Contacted','Responded','Qualified','Proposal Sent','Negotiation','Won','Lost'];
export const stages = ['New Opportunity','Requirement Received','Qualified','Proposal Preparation','Proposal Sent','Negotiation','NDA / Contract','Won','Lost','On Hold'];
export const salesRoleNames = ['Sales Head','Sales Manager','Senior BDE','BDA','Sales Coordinator','Read-only Auditor'];
export const actions = ['view','create','edit','delete','export','assign','approve'];
const f = (key,label,type='text',options,required=false,ref) => ({key,label,type,options,required,ref});
const select = (key,label,options,required=false) => f(key,label,'select',options,required);
const reference = (key,label,ref,required=false) => f(key,label,'reference',undefined,required,ref);
const company = () => reference('company','Company','companies',true);
const contact = () => reference('contact','Contact','contacts');
const lead = () => reference('lead','Related Lead','leads');
const deal = () => reference('deal','Related Deal','deals');
const owner = () => reference('assignedTo','Assigned BDA / Sales Owner','users');
const notes = () => f('notes','Notes','textarea');
const currency = () => select('currency','Currency',['INR','USD','EUR','GBP']);
const service = () => select('serviceCategory','Service Category',services);
const money = (key,label) => f(key,label,'number');
const status = (options) => select('status','Status',options);
const date = (key,label) => f(key,label,'date');
const time = (key,label) => f(key,label,'datetime-local');
const bool = (key,label) => f(key,label,'checkbox');
const module = (title,collection,fields,description) => ({title,collection,fields,description:description || 'Manage records, relationships and activity for your sales workflow.'});
export const resources = {
  companies: module('Companies','sales_companies',[f('name','Company Name','text',undefined,true),f('website','Company Website','url'),f('industry','Industry'),f('country','Country'),f('city','City'),f('linkedinUrl','LinkedIn URL','url'),owner(),notes()]),
  leads: module('Companies / Leads','sales_leads',[company(),f('name','Company / Lead Name','text',undefined,true),f('website','Company Website','url'),f('industry','Industry'),f('country','Country'),f('city','City'),f('contactName','Contact Person'),f('email','Email','email'),f('phone','Phone'),f('linkedinUrl','LinkedIn URL','url'),service(),f('leadSource','Lead Source'),status(leadStatuses),select('priority','Priority',['Low','Medium','High','Urgent']),owner(),time('lastContacted','Last Contacted'),time('nextFollowup','Next Follow-up'),notes()]),
  contacts: module('Client Contacts','sales_contacts',[f('name','Contact Name','text',undefined,true),company(),f('jobTitle','Job Title'),f('department','Department'),f('email','Email','email'),f('phone','Phone'),f('whatsapp','WhatsApp'),f('linkedinUrl','LinkedIn','url'),f('country','Country'),f('timeZone','Time Zone'),bool('decisionMaker','Decision Maker'),owner(),time('lastInteraction','Last Interaction'),notes()]),
  research: module('Lead Research','sales_research',[f('name','Researched Company','text',undefined,true),f('website','Company Website','url'),f('linkedinUrl','LinkedIn Profile','url'),select('industry','Industry',['AI/ML','Software Development','IT Services','SaaS','Healthcare AI','FinTech','EdTech','E-commerce','BPO','Data Annotation Companies']),f('contactName','Decision Maker'),f('email','Decision-Maker Email','email'),f('country','Country'),service(),f('sourceUrl','Authorized Source URL','url'),notes(),owner()], 'Record verified manual research. Open source websites yourself; no external facts are generated.'),
  qualifications: module('Lead Qualification','sales_qualifications',[company(),reference('lead','Lead','leads',true),f('requirement','Client Requirement','textarea',undefined,true),money('budget','Project Budget'),f('volume','Expected Project Volume'),date('expectedStart','Expected Start Date'),bool('decisionMaker','Decision Maker Identified'),f('timeline','Timeline'),bool('serviceMatch','Service Match'),bool('resourceAvailability','Resource Availability'),money('estimatedValue','Estimated Deal Value'),f('score','Qualification Score','number'),status(['Pending','Qualified','Disqualified','More Information Requested']),owner(),notes()]),
  deals: module('Deals / Opportunities','sales_deals',[company(),lead(),service(),f('name','Project Name','text',undefined,true),f('description','Project Description','textarea'),f('volume','Estimated Volume'),currency(),money('estimatedValue','Estimated Value'),date('expectedClosing','Expected Closing Date'),f('probability','Probability %','number'),owner(),select('stage','Stage',stages),notes()]),
  activities: module('Communication History','sales_activities',[company(),contact(),lead(),deal(),select('type','Communication Type',['Note','Email','Reply','Call','Meeting','Follow-up','Proposal','Status Change']),f('summary','Summary','textarea',undefined,true),time('occurredAt','Interaction Date'),owner()]),
  emails: module('Email Outreach','sales_emails',[reference('company','Company','companies'),contact(),deal(),f('to','To','email',undefined,true),f('cc','CC (comma-separated)'),f('bcc','BCC (comma-separated)'),f('subject','Subject','text',undefined,true),f('body','Message Body','textarea',undefined,true),status(['Draft','Scheduled','Sending','Sent','Failed','Reply','Template']),time('scheduledAt','Scheduled Date'),owner()], 'Compose and send through the configured SMTP provider. Sent means provider accepted; delivery and replies require real evidence.'),
  linkedin: module('LinkedIn Outreach','sales_linkedin',[company(),f('name','Contact Name','text',undefined,true),f('linkedinUrl','LinkedIn Prospect URL','url',undefined,true),select('connectionStatus','Connection Status',['Not Connected','Requested','Connected']),f('message','Message Template','textarea'),date('outreachDate','Outreach Date'),select('replyStatus','Reply Status',['No Reply','Replied','Interested','Not Interested']),time('nextFollowup','Follow-up Date'),owner(),notes()], 'Open LinkedIn profiles manually and record your own outreach. No scraping or automated messaging.'),
  calls: module('Calls & Communication','sales_calls',[company(),contact(),lead(),f('phone','Phone'),select('callType','Call Type',['Outbound','Inbound']),time('occurredAt','Call Date'),f('duration','Call Duration (minutes)','number'),select('outcome','Call Outcome',['Connected','No Answer','Busy','Interested','Not Interested','Callback Requested']),f('summary','Discussion Summary','textarea',undefined,true),f('nextAction','Next Action'),time('nextFollowup','Follow-up Date'),owner(),notes()]),
  meetings: module('Meetings & Calendar','sales_meetings',[f('name','Meeting Title','text',undefined,true),company(),contact(),lead(),deal(),time('startsAt','Start Date & Time'),time('endsAt','End Date & Time'),f('timeZone','Time Zone'),select('platform','Meeting Platform',['Google Meet','Microsoft Teams','Zoom','Phone','In Person','Other']),f('meetingUrl','Meeting Link','url'),f('agenda','Agenda','textarea'),f('attendees','Assigned Employees','references',undefined,false,'users'),status(['Scheduled','Completed','Cancelled']),owner(),notes(),f('nextSteps','Next Steps','textarea')]),
  followups: module('Follow-ups','sales_followups',[f('name','Follow-up Title','text',undefined,true),company(),contact(),lead(),deal(),owner(),time('dueDate','Due Date'),select('priority','Priority',['Low','Medium','High','Urgent']),select('type','Follow-up Type',['Email','Call','LinkedIn','Meeting','Other']),status(['Pending','Completed','Cancelled']),notes()]),
  proposals: module('Proposals & Quotations','sales_proposals',[company(),reference('deal','Related Deal','deals',true),f('name','Project Name','text',undefined,true),service(),select('unit','Unit',['Per Hour','Per Minute','Per Image','Per Task','Per Word','Per Project','Per Resource/Month']),money('quantity','Quantity'),money('unitRate','Unit Rate'),currency(),money('tax','Tax %'),money('discount','Discount Amount'),f('deliveryTimeline','Delivery Timeline'),f('paymentTerms','Payment Terms','textarea'),date('validUntil','Validity Date'),status(['Draft','Pending Approval','Approved','Sent','Accepted','Rejected','Expired']),f('recipient','Client Email','email'),owner(),notes()]),
  pricing: module('Pricing & Rate Cards','sales_rate_cards',[f('name','Rate Name','text',undefined,true),select('serviceCategory','Service',['Audio Recording','Transcription','Translation','Annotation','Image Collection','Video Collection','LLM Evaluation','Software Development','Website Development','Mobile App Development','Dedicated Developers']),select('unit','Pricing Unit',['Per Hour','Per Minute','Per Image','Per Task','Per Word','Per Project','Per Resource/Month']),money('unitRate','Unit Rate'),currency(),date('effectiveDate','Effective Date'),status(['Draft','Pending Approval','Approved','Retired']),owner(),notes()]),
  contracts: module('NDA / MSA / SOW','sales_contracts',[f('name','Document Name','text',undefined,true),company(),deal(),select('documentType','Document Type',['NDA','MSA','SOW','Service Agreement','Purchase Order']),date('sentDate','Sent Date'),date('signedDate','Signed Date'),date('effectiveDate','Effective Date'),date('expiryDate','Expiry Date'),status(['Draft','Under Review','Sent','Signed','Rejected','Expired']),f('signatureEvidence','Signature Verification Notes','textarea'),owner(),notes()], 'Upload private documents. A manager must verify uploaded signature evidence before marking a contract signed.'),
  onboarding: module('Client Onboarding','sales_onboarding',[f('name','Onboarding Name','text',undefined,true),company(),reference('deal','Won Deal','deals',true),bool('companyDetails','Company Details'),bool('contactsVerified','Client Contact Verification'),bool('requirementsConfirmed','Requirements Confirmed'),bool('commercialApproved','Commercial Terms Approved'),bool('ndaSigned','NDA Signed'),bool('agreementSigned','MSA/SOW Signed'),bool('poRequired','Purchase Order Required'),bool('poReceived','Purchase Order Received'),bool('billingCollected','Billing Details Collected'),reference('projectManager','Project Manager','employees'),bool('kickoffScheduled','Kickoff Meeting Scheduled'),status(['In Progress','Completed']),owner(),notes()]),
  handovers: module('Project Handover','sales_handovers',[f('name','Project Name','text',undefined,true),company(),reference('deal','Won Deal','deals',true),service(),f('volume','Project Volume'),f('languages','Languages (comma-separated)'),date('startDate','Start Date'),date('deadline','Deadline'),money('approvedRate','Approved Rate'),currency(),f('scope','Scope of Work','textarea',undefined,true),f('guidelines','Guidelines','textarea'),f('deliverables','Deliverables','textarea'),f('qaRequirements','QA Requirements','textarea'),reference('projectManager','Assigned Project Manager','employees'),status(['Draft','Pending Review','Approved']),owner(),notes()]),
  targets: module('Targets & KPIs','sales_targets',[f('name','Target Period','text',undefined,true),owner(),date('periodStart','Period Start'),date('periodEnd','Period End'),money('dailyLeads','Daily Lead Target'),money('weeklyOutreach','Weekly Outreach Target'),money('monthlyMeetings','Monthly Meeting Target'),money('qualifiedLeads','Qualified Lead Target'),money('proposals','Proposal Target'),money('revenue','Revenue Target'),money('dealsWon','Deal Closing Target'),currency(),notes()]),
  team: module('Sales Team','sales_team',[reference('user','Existing CRM User','users',true),reference('employee','Existing Employee','employees'),f('designation','Designation'),f('department','Department'),reference('reportingManager','Reporting Manager','users'),select('vertical','Sales Vertical',['AI/ML Services','Software Development','IT Consulting','Digital Services']),money('monthlyTarget','Monthly Target'),status(['Active','Inactive']),owner()], 'Link existing CRM accounts and employees; credentials and employee records remain in the existing CRM.'),
  permissions: module('Roles & Permissions','sales_permissions',[reference('user','CRM User','users',true),select('salesRole','Sales Role',salesRoleNames,true),f('grants','Module Permissions JSON','json')], 'Manage per-user View, Create, Edit, Delete, Export, Assign and Approve permissions. Administrative permissions require a CRM administrator.'),
  settings: module('Sales Settings','sales_settings',[f('name','Settings Name','text',undefined,true),currency(),f('timeZone','Time Zone'),f('leadStatuses','Custom Lead Statuses','json'),f('dealStages','Custom Deal Stages','json'),f('leadSources','Lead Sources','json'),f('serviceCategories','Service Categories','json'),f('followupRules','Follow-up Rules','json'),f('notificationPreferences','Notification Preferences','json'),bool('duplicateDetection','Duplicate Detection'),f('approvalWorkflows','Approval Workflows','json'),f('integrations','Integration Details (no secrets)','textarea')]),
};
export const navigation = [
  ['Overview',[['dashboard','Sales Dashboard'],['analytics','Sales Analytics']]],
  ['Lead Management',[['leads','Companies / Leads'],['contacts','Client Contacts'],['research','Lead Research'],['qualification','Lead Qualification'],['assigned-leads','Assigned Leads']]],
  ['Outreach & Communication',[['email-outreach','Email Outreach'],['linkedin-outreach','LinkedIn Outreach'],['calls','Calls & Communication'],['meetings','Meetings & Calendar'],['follow-ups','Follow-ups'],['communications','Communication History']]],
  ['Sales Pipeline',[['deals','Deals / Opportunities'],['proposals','Proposals & Quotations'],['pricing','Pricing & Rate Cards'],['contracts','NDA / MSA / SOW'],['client-onboarding','Client Onboarding'],['handover','Project Handover']]],
  ['Performance & Reports',[['targets','Targets & KPIs'],['team-performance','Team Performance'],['revenue','Revenue & Forecast'],['reports','Sales Reports']]],
  ['Administration',[['team','Sales Team'],['permissions','Roles & Permissions'],['settings','Sales Settings']]],
];
export const pageResources = {'qualification':'qualifications','assigned-leads':'leads','email-outreach':'emails','linkedin-outreach':'linkedin','follow-ups':'followups','communications':'activities','client-onboarding':'onboarding','handover':'handovers'};
export const onboardingChecks = ['companyDetails','contactsVerified','requirementsConfirmed','commercialApproved','ndaSigned','agreementSigned','billingCollected','kickoffScheduled'];
export const salesAccessActions = ['view','create','edit','delete','export','approve'];
export const salesAccessModules = navigation.flatMap(([section,items])=>items.map(([page,label])=>({key:'sales-'+page,page,label,section,resource:pageResources[page] || (['dashboard','analytics','reports','team-performance'].includes(page)?'leads':page==='revenue'?'deals':page)})));
export const salesResourceAccessKey = resource => resource==='companies'?'sales-leads':salesAccessModules.find(item=>item.resource===resource&&!['dashboard','analytics','reports','team-performance','assigned-leads','revenue'].includes(item.page))?.key || 'sales-'+resource;
