import { useEffect,useState } from 'react';
import { useSearchParams } from 'react-router-dom';
import { Download,ChevronLeft,ChevronRight } from 'lucide-react';
import toast from 'react-hot-toast';
import { salesApi,salesDownload,display } from './api.js';
const names={daily:'Daily BDA Activity Report',weekly:'Weekly Sales Report',monthly:'Monthly Sales Report',sources:'Lead Source Report',followups:'Follow-up Report',conversion:'Conversion Report',deals:'Deal Report',revenue:'Revenue Report',employees:'Employee Performance Report'};
export default function SalesReports({metadata}) {
  const [params,setParams]=useSearchParams(),[data,setData]=useState(null),[error,setError]=useState(''),[loading,setLoading]=useState(false),[search,setSearch]=useState('');
  const type=params.get('type') || 'daily',query=params.toString()+'&type='+type;
  useEffect(()=>{let current=true;setLoading(true);setError('');salesApi('/reports?'+query).then(result=>{if(current)setData(result);}).catch(err=>{if(current)setError(err.message);}).finally(()=>{if(current)setLoading(false);});return ()=>{current=false;};},[query]);
  function choose(kind){setSearch('');setParams(current=>{const next=new URLSearchParams(current);next.set('type',kind);next.set('page','1');return next;},{replace:true});}
  const rows=data?.rows.filter(row=>!search||JSON.stringify(row).toLowerCase().includes(search.toLowerCase())) || [];
  return <section className="space-y-5"><div className="grid gap-3 sm:grid-cols-2 lg:grid-cols-3">{Object.entries(names).map(([key,label])=><button key={key} className={'rounded-xl border p-4 text-left text-sm font-semibold '+(type===key?'border-indigo-300 bg-indigo-50 text-[#403DF0]':'bg-white')} onClick={()=>choose(key)}>{label}</button>)}</div><div className="flex flex-wrap items-center gap-3"><h2 className="mr-auto text-lg font-bold">{names[type]}</h2><input value={search} onChange={event=>setSearch(event.target.value)} placeholder="Search current report page…" aria-label="Search report" className="rounded-lg border px-3 py-2 text-sm"/>{metadata.pages?.reports?.export&&metadata.permissions[data?.resource]?.export&&['xlsx','csv','pdf'].map(format=><button className="btn-secondary" key={format} onClick={()=>salesDownload('/reports/export?'+query+'&format='+format,'sales-'+type+'.'+format).catch(err=>toast.error(err.message))}><Download className="mr-1 h-4 w-4"/>{format.toUpperCase()}</button>)}</div>{error?<p role="alert" className="rounded-xl bg-rose-50 p-4 text-sm text-rose-700">{error}</p>:loading?<div className="h-48 animate-pulse rounded-xl bg-slate-200"/>:<div className="max-h-[65vh] overflow-auto rounded-2xl border bg-white"><table className="w-full whitespace-nowrap text-left text-xs"><thead className="sticky top-0 bg-slate-50"><tr>{data?.fields.map(field=><th key={field.key} className="px-4 py-3 capitalize">{field.label}</th>)}</tr></thead><tbody>{rows.map((row,index)=><tr key={row._id || index} className="border-t hover:bg-slate-50">{data.fields.map(field=><td key={field.key} className="max-w-64 truncate px-4 py-3">{display(row[field.key],field.type)}</td>)}</tr>)}</tbody></table>{!rows.length&&<p className="p-10 text-center text-sm text-slate-400">No report records match this period.</p>}</div>}<div className="flex items-center justify-between text-sm text-slate-500"><span>{data?.total || 0} rows · Page {data?.page || 1} of {Math.max(1,data?.pages || 1)}</span><div className="flex gap-2">{[-1,1].map(step=><button key={step} className="btn-secondary" aria-label={step<0?'Previous report page':'Next report page'} disabled={loading||step<0&&(data?.page || 1)<=1||step>0&&(data?.page || 1)>=(data?.pages || 1)} onClick={()=>setParams(current=>{const next=new URLSearchParams(current);next.set('page',String((data?.page || 1)+step));return next;},{replace:true})}>{step<0?<ChevronLeft className="h-4 w-4"/>:<ChevronRight className="h-4 w-4"/>}</button>)}</div></div></section>;
}